import PDFDocument from 'pdfkit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const reportsDir = path.join(__dirname, '../reports');

try {
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }
} catch (err) {
  console.warn(`Could not create reports directory: ${err.message}`);
}

export const generatePredictionReport = async ({ user, prediction, imagePath }) => {
  const fileName = `report-${prediction._id}-${Date.now()}.pdf`;
  const reportPath = path.join(reportsDir, fileName);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(reportPath);

    doc.pipe(stream);

    doc.fontSize(22).text('Oral Health Analysis Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.moveDown(2);

    doc.fontSize(14).text('Patient Information', { underline: true });
    doc.fontSize(11).text(`Name: ${user.name}`);
    doc.text(`Email: ${user.email}`);
    if (user.age) doc.text(`Age: ${user.age}`);
    if (user.gender) doc.text(`Gender: ${user.gender}`);
    doc.moveDown();

    doc.fontSize(14).text('Prediction Result', { underline: true });
    doc.fontSize(11).text(`Disease: ${prediction.diseaseName}`);
    doc.text(`Confidence: ${prediction.confidence.toFixed(2)}%`);
    doc.text(`Severity: ${prediction.severity}`);
    doc.moveDown();

    if (prediction.description) {
      doc.fontSize(14).text('Description', { underline: true });
      doc.fontSize(11).text(prediction.description);
      doc.moveDown();
    }

    if (fs.existsSync(imagePath)) {
      doc.fontSize(14).text('Uploaded Image', { underline: true });
      doc.moveDown(0.5);
      try {
        doc.image(imagePath, { fit: [400, 300], align: 'center' });
      } catch {
        doc.fontSize(10).text('Image could not be embedded in report.');
      }
      doc.moveDown();
    }

    if (prediction.treatmentSuggestions?.length) {
      doc.fontSize(14).text('Treatment Suggestions', { underline: true });
      prediction.treatmentSuggestions.forEach((item) => doc.fontSize(11).text(`• ${item}`));
      doc.moveDown();
    }

    if (prediction.preventionTips?.length) {
      doc.fontSize(14).text('Oral Care Tips', { underline: true });
      prediction.preventionTips.forEach((item) => doc.fontSize(11).text(`• ${item}`));
      doc.moveDown();
    }

    if (prediction.recommendation) {
      doc.fontSize(14).text('Recommendations', { underline: true });
      doc.fontSize(11).text(prediction.recommendation);
    }

    doc.moveDown(2);
    doc.fontSize(9).fillColor('gray').text(
      'Disclaimer: This report is generated by an AI system and is not a substitute for professional dental diagnosis.',
      { align: 'center' }
    );

    doc.end();

    stream.on('finish', () => resolve({ reportPath, fileName }));
    stream.on('error', reject);
  });
};

export default { generatePredictionReport };
